# Generated by Django 5.2.2 on 2025-06-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('guest', 'guest'), ('admin', 'admin'), ('doctor', 'doctor'), ('patient', 'patient')], default='guest', max_length=10)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
