# Generated by Django 5.2.2 on 2025-06-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('outdated', 'Outdated')], default='pending', max_length=15)),
                ('day', models.CharField(choices=[('sat', 'Saturday'), ('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday')], max_length=20)),
                ('date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('reason_of_visit', models.TextField(blank=True, max_length=200)),
                ('reason_of_cancellation', models.TextField(blank=True, max_length=200)),
                ('doctor_notes', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
