# Generated by Django 5.2.2 on 2025-06-06 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('patient_image_path', models.ImageField(upload_to='patient_images/')),
                ('phone', models.CharField(max_length=17)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
