# Generated by Django 5.2.2 on 2025-06-06 12:36

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('doctor_image_path', models.ImageField(upload_to='doctor/images/')),
                ('national_id_image_path', models.ImageField(upload_to='doctor/national_ids/')),
                ('background_image_path', models.ImageField(upload_to='doctor/backgrounds/')),
                ('doctor_bio', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('doctor_availability', models.BooleanField(default=False)),
                ('available_days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('sat', 'Saturday'), ('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday')], max_length=3), blank=True, default=list, size=None)),
                ('specializations', models.ManyToManyField(related_name='doctors', to='doctor.specialization')),
            ],
        ),
    ]
